# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FWOD
                                 A QGIS plugin
 OD反推
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-03
        copyright            : (C) 2022 by huanghongpu
        email                : 552477136@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FWOD class from file FWOD.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fw_od import FWOD
    from .read import read_notoll
    from .graph import Network
    from copy import deepcopy
    from .FW import calc_RG
    from .OD import equili_esti
    return FWOD(iface)
